#!/bin/sh

#conan export  Alembic_1.7.12/conanfile.py                      Alembic/1.7.12@mercseng/v1
#conan export  b2_4.2.0/conanfile.py                            b2/4.2.0@mercseng/v0
#conan export  bison_3.5.3/conanfile.py                         bison/3.5.3@mercseng/v0
#conan export  blosc_1.11.2/conanfile.py                        blosc/1.11.2@mercseng/v0
#conan export  boost_1.73.0/conanfile.py                        boost/1.73.0@mercseng/v1
#conan export  bzip2_1.0.8/conanfile.py                         bzip2/1.0.8@mercseng/v0
#conan export  catch2_3.0.0-preview3/conanfile.py               catch2/3.0.0-preview3@mercseng/v0
#conan export  cmake_3.17.3/conanfile.py                        cmake/3.17.3@mercseng/v0
#conan export  cpython_3.7.7/conanfile.py                       cpython/3.7.7@mercseng/v0
#conan export  double-conversion_3.1.5/conanfile.py             double-conversion/3.1.5@mercseng/v0
#conan export  eigen_3.3.7/conanfile.py                         eigen/3.3.7@mercseng/v0
#conan export  embree_3.9.0/conanfile.py                        embree/3.9.0@mercseng/v2
#conan export  expat_2.2.9/conanfile.py                         expat/2.2.9@mercseng/v0
#conan export  FBX_2020.0.1/conanfile.py                        FBX/2020.0.1@mercseng/v0
#conan export  flex_2.6.4/conanfile.py                          flex/2.6.4@mercseng/v0
#conan export  fontstash_1.0.1/conanfile.py                     fontstash/1.0.1@mercseng/v0
#conan export  freetype_2.10.2_with_Harfbuzz/conanfile.py       freetype/2.10.2_with_Harfbuzz@mercseng/v0
#conan export  fumefx_4.0/conanfile.py                          fumefx/4.0@mercseng/v0
#conan export  gdbm_1.18.1/conanfile.py                         gdbm/1.18.1@mercseng/v0
#conan export  glew_2.1.0/conanfile.py                          glew/2.1.0@mercseng/v0
#conan export  glfw_3.3/conanfile.py                            glfw/3.3@mercseng/v0
#conan export  glu_9.0.1/conanfile.py                           glu/9.0.1@mercseng/v0
#conan export  GSL_2.1.0/conanfile.py                           GSL/2.1.0@mercseng/v0
#conan export  hdf5_1.10.6/conanfile.py                         hdf5/1.10.6@mercseng/v0
#conan export  FFmpeg_4.3.1/conanfile.py                        FFmpeg/4.3.1@mercseng/v0
#conan export  ispc_1.13.0/conanfile.py                         ispc/1.13.0@mercseng/v0
#conan export  ispc_1.9.2/conanfile.py                          ispc/1.9.2@mercseng/v0
#conan export  jbig_20160605/conanfile.py                       jbig/20160605@mercseng/v0
#conan export  jemalloc_4.3.1/conanfile.py                      jemalloc/4.3.1@mercseng/v0
#conan export  jom_installer_1.1.2/conanfile.py                 jom_installer/1.1.2@mercseng/v0
#conan export  libalsa_1.2.2/conanfile.py                       libalsa/1.2.2@mercseng/v0
#conan export  libcurl_7.71.0/conanfile.py                       libcurl/7.71.0@mercseng/v1
#conan export  libffi_3.3/conanfile.py                          libffi/3.3@mercseng/v0
#conan export  libiconv_1.15/conanfile.py                       libiconv/1.15@mercseng/v0
#conan export  libjpeg-turbo_1.5.2/conanfile.py                 libjpeg-turbo/1.5.2@mercseng/v0
#conan export  libpng_1.6.37/conanfile.py                       libpng/1.6.37@mercseng/v0
#conan export  libsndfile_1.0.29/conanfile.py                   libsndfile/1.0.29@mercseng/v0
#conan export  libtiff_4.0.9/conanfile.py                       libtiff/4.0.9@mercseng/v0
#conan export  libunwind_1.3.1/conanfile.py                     libunwind/1.3.1@mercseng/v0
#conan export  libuuid_1.0.3/conanfile.py                       libuuid/1.0.3@mercseng/v0
#conan export  libwebp_1.1.0/conanfile.py                       libwebp/1.1.0@mercseng/v0
#conan export  libxml2_2.9.9/conanfile.py                       libxml2/2.9.9@mercseng/v0
#conan export  llvm_3.5.1/conanfile.py                          llvm/3.5.1@mercseng/v0
#conan export  lzma_5.2.4/conanfile.py                          lzma/5.2.4@mercseng/v0
#conan export  m4_1.4.18/conanfile.py                           m4/1.4.18@mercseng/v0
#conan export  materialx_1.37.1/conanfile.py                    materialx/1.37.1@mercseng/v0
#conan export  nasm_2.13.02/conanfile.py                        nasm/2.13.02@mercseng/v0
#conan export  ncurses_6.2/conanfile.py                         ncurses/6.2@mercseng/v0
#conan export  ninja_1.10.0/conanfile.py                        ninja/1.10.0@mercseng/v0
#conan export  OpenColorIO_1.1.1/conanfile.py                   OpenColorIO/1.1.1@mercseng/v0
#conan export  OpenEXR_2.5.1/conanfile.py                       OpenEXR/2.5.1@mercseng/v0
#conan export  OpenExrId_1.0-beta.22/conanfile.py               OpenExrId/1.0-beta.22@mercseng/v0
#conan export  OpenImageDenoise_1.0.0/conanfile.py              OpenImageDenoise/1.0.0@mercseng/v2
#conan export  OpenImageIO_2.1.15.0/conanfile.py                OpenImageIO/2.1.15.0@mercseng/v3
#conan export  OpenSSL_1.1.1g/conanfile.py                      OpenSSL/1.1.1g@mercseng/v0
#conan export  OpenSubdiv_3.4.3/conanfile.py                    OpenSubdiv/3.4.3@mercseng/v1
#conan export  OpenVdb_4.0.2/conanfile.py                       OpenVdb/4.0.2@mercseng/v1
#conan export  OpenVdb_6.2.1/conanfile.py                       OpenVdb/6.2.1@mercseng/v1
#conan export  partio_1.7.4/conanfile.py                        partio/1.7.4@mercseng/v0
#conan export  pcre2_10.33/conanfile.py                         pcre2/10.33@mercseng/v0
#conan export  PortAudio_2018-12-24/conanfile.py                PortAudio/2018-12-24@mercseng/v0
#conan export  ptex_2.3.2/conanfile.py                          ptex/2.3.2@mercseng/v0
#conan export  pybind11_2.5.0/conanfile.py                      pybind11/2.5.0@mercseng/v0
#conan export  PySide2_5.12.6/conanfile.py                       PySide2/5.12.6@mercseng/v2
#conan export  python_2.6/conanfile.py                          python/2.6@mercseng/v1
#conan export  python_3.7/conanfile.py                          python3/3.7@mercseng/v0
#conan export  qt_5.12.6/conanfile.py                            qt/5.12.6@mercseng/v1
#conan export  rapidjson_1.1.0/conanfile.py                     rapidjson/1.1.0@mercseng/v0
#conan export  re2_2019-06-01/conanfile.py                      re2/2019-06-01@mercseng/v0
#conan export  readline_8.0/conanfile.py                        readline/8.0@mercseng/v0
#conan export  rumba-python_1.0.0/conanfile.py                  rumba-python/1.0.0@mercseng/v1
#conan export  rumba-python-dev_1.0.0/conanfile.py              rumba-python-dev/1.0.0@mercseng/v0
#conan export  spdlog-rumba_1.5.0/conanfile.py                  spdlog-rumba/1.5.0@mercseng/v0
#conan export  sqlite3_3.32.3/conanfile.py                      sqlite3/3.32.3@mercseng/v0
#conan export  tbb_2020.02/conanfile.py                         tbb/2020.02@mercseng/v2
#conan export  unistd_1.0/conanfile.py                         unistd/1.0@mercseng/v0
#conan export  USD_20.05/conanfile.py                           USD/20.05@mercseng/v4
#conan export  USD_20.11/conanfile.py                           USD/20.11@mercseng/v1
#conan export  USD_20.11-rumba/conanfile.py                     USD/20.11-rumba@mercseng/v4
#conan export  winflexbison_2.5.22/conanfile.py                 winflexbison/2.5.22@mercseng/v0
#conan export  wxwidgets_2.8.12/conanfile.py                    wxwidgets/2.8.12@mercseng/v0
#conan export  zlib_1.2.11/conanfile.py                         zlib/1.2.11@mercseng/v0
#conan export  zstd_1.4.5/conanfile.py                          zstd/1.4.5@mercseng/v0
