#!/bin/sh

conan export Alembic_1.7.3/conanfile.py Alembic/1.7.3@pierousseau/stable
conan export blosc_1.11.2/conanfile.py blosc/1.11.2@pierousseau/stable
conan export embree_3.5.2/conanfile.py embree/3.5.2@pierousseau/stable
conan export embree_3.8.0/conanfile.py embree/3.8.0@pierousseau/stable
conan export freetype_2.9.1_with_Harfbuzz/conanfile.py freetype/2.9.1_with_Harfbuzz@pierousseau/stable
conan export fumefx_guerillaBinaries_4/conanfile.py fumefx/guerillaBinaries_4@pierousseau/stable
conan export glew_2.1.0/conanfile.py glew/2.1.0@pierousseau/stable
conan export glfw_3.3/conanfile.py glfw/3.3@pierousseau/stable
conan export hdf5_1.10.1/conanfile.py hdf5/1.10.1@pierousseau/stable
conan export IlmBase_2.2.0/conanfile.py IlmBase/2.2.0@pierousseau/stable
conan export jemalloc_4.3.1/conanfile.py jemalloc/4.3.1@pierousseau/stable
conan export libiconv_1.15/conanfile.py libiconv/1.15@pierousseau/stable
conan export libjpeg-turbo_1.5.2/conanfile.py libjpeg-turbo/1.5.2@pierousseau/stable
conan export libpng_1.6.37/conanfile.py libpng/1.6.37@pierousseau/stable
conan export libxml2_2.9.9/conanfile.py libxml2/2.9.9@pierousseau/stable
conan export llvm_3.5.1/conanfile.py llvm/3.5.1@pierousseau/stable
conan export nasm_2.13.01/conanfile.py nasm/2.13.01@pierousseau/stable
conan export materialx_1.36.3/conanfile.py materialx/1.36.3@pierousseau/stable
conan export OpenColorIO_1.1.1/conanfile.py OpenColorIO/1.1.1@pierousseau/stable
conan export OpenEXR_2.2.0/conanfile.py OpenEXR/2.2.0@pierousseau/stable
conan export OpenExrId_1.0-beta.11/conanfile.py OpenExrId/1.0-beta.11@pierousseau/stable
conan export OpenExrId_1.0-beta.17/conanfile.py OpenExrId/1.0-beta.17@pierousseau/stable
conan export OpenExrId_1.0-beta.20/conanfile.py OpenExrId/1.0-beta.20@pierousseau/stable
conan export OpenFx_1.4/conanfile.py OpenFx/1.4@pierousseau/stable
conan export OpenImageDenoise_1.0.0/conanfile.py OpenImageDenoise/1.0.0@pierousseau/stable
conan export OpenImageIO_1.6.18/conanfile.py OpenImageIO/1.6.18@pierousseau/stable
conan export OpenVdb_4.0.2/conanfile.py OpenVdb/4.0.2@pierousseau/stable
conan export partio_1.7.4/conanfile.py partio/1.7.4@pierousseau/stable
conan export ptex_2.3.2/conanfile.py ptex/2.3.2@pierousseau/stable
conan export python_guerillaBinaries_2.6/conanfile.py python/guerillaBinaries_2.6@pierousseau/stable
conan export re2_2016-02-01/conanfile.py re2/2016-02-01@pierousseau/stable
conan export re2_2019-06-01/conanfile.py re2/2019-06-01@pierousseau/stable
conan export USD_19.05/conanfile.py USD/19.05@pierousseau/stable
conan export USD_20.02/conanfile.py USD/20.02@pierousseau/stable
conan export TBB_2019_U6/conanfile.py TBB/2019_U6@pierousseau/stable
conan export wxwidgets_2.8.12/conanfile.py wxwidgets/2.8.12@pierousseau/stable
conan export zlib_1.2.11/conanfile.py zlib/1.2.11@pierousseau/stable
