#!/bin/sh

export REPO="mercenaries"

#conan upload Alembic/1.7.12@mercseng/v1                                         -r $REPO --all --confirm
#conan upload b2/4.2.0@mercseng/v0                                               -r $REPO --all --confirm
#conan upload bison/3.5.3@mercseng/v0                                            -r $REPO --all --confirm
#conan upload blosc/1.11.2@mercseng/v0                                           -r $REPO --all --confirm
#conan upload boost/1.73.0@mercseng/v6                                           -r $REPO --all --confirm
#conan upload bzip2/1.0.8@mercseng/v0                                            -r $REPO --all --confirm
#conan upload catch2/3.0.0-preview3@mercseng/v0                                  -r $REPO --all --confirm
#conan upload cmake/3.17.3@mercseng/v0                                           -r $REPO --all --confirm
#conan upload cmake/3.28.1@mercseng/v0                                           -r $REPO --all --confirm
#conan upload cpython/3.7.7@mercseng/v1                                          -r $REPO --all --confirm
#conan upload double-conversion/3.1.5@mercseng/v0                                -r $REPO --all --confirm
#conan upload eigen/3.3.7@mercseng/v0                                            -r $REPO --all --confirm
#conan upload embree/3.9.0@mercseng/v2                                           -r $REPO --all --confirm
#conan upload expat/2.2.9@mercseng/v0                                            -r $REPO --all --confirm
#conan upload FBX/2020.0.1@mercseng/v0                                           -r $REPO --all --confirm
#conan upload FBX/2020.2.1@mercseng/v0                                           -r $REPO --all --confirm
#conan upload FFmpeg/4.3.1@mercseng/v2                                           -r $REPO --all --confirm
#conan upload flex/2.6.4@mercseng/v0                                             -r $REPO --all --confirm
#conan upload fontstash/1.0.1@mercseng/v0                                        -r $REPO --all --confirm
#conan upload freetype/2.11.1_with_Harfbuzz@mercseng/v0                          -r $REPO --all --confirm
#conan upload fumefx/4.0@mercseng/v0                                             -r $REPO --all --confirm
#conan upload gdbm/1.18.1@mercseng/v0                                            -r $REPO --all --confirm
#conan upload glew/2.1.0@mercseng/v0                                             -r $REPO --all --confirm
#conan upload glfw/3.3@mercseng/v0                                               -r $REPO --all --confirm
#conan upload glu/9.0.1@mercseng/v0                                              -r $REPO --all --confirm
#conan upload GSL/2.1.0@mercseng/v0                                              -r $REPO --all --confirm
#conan upload hdf5/1.10.6@mercseng/v0                                            -r $REPO --all --confirm
#conan upload icu/64.2@mercseng/v2                                               -r $REPO --all --confirm
#conan upload ispc/1.14.1@mercseng/v0                                            -r $REPO --all --confirm
#conan upload ispc/1.13.0@mercseng/v0                                            -r $REPO --all --confirm
#conan upload ispc/1.9.2@mercseng/v0                                             -r $REPO --all --confirm
#conan upload jbig/20160605@mercseng/v0                                          -r $REPO --all --confirm
#conan upload jemalloc/4.3.1@mercseng/v0                                         -r $REPO --all --confirm
#conan upload jom_installer/1.1.2@mercseng/v0                                    -r $REPO --all --confirm
#conan upload libalsa/1.2.2@mercseng/v1                                          -r $REPO --all --confirm
#conan upload libcurl/7.71.0@mercseng/v1                                         -r $REPO --all --confirm
#conan upload libffi/3.3@mercseng/v0                                             -r $REPO --all --confirm
#conan upload libiconv/1.15@mercseng/v1                                          -r $REPO --all --confirm
#conan upload libjpeg-turbo/1.5.2@mercseng/v0                                    -r $REPO --all --confirm
#conan upload libpng/1.6.37@mercseng/v0                                          -r $REPO --all --confirm
#conan upload libsndfile/1.0.29@mercseng/v0                                      -r $REPO --all --confirm
#conan upload libsquish/1.10@mercseng/v1                                         -r $REPO --all --confirm
#conan upload libtiff/4.0.9@mercseng/v0                                          -r $REPO --all --confirm
#conan upload libunwind/1.3.1@mercseng/v0                                        -r $REPO --all --confirm
#conan upload libuuid/1.0.3@mercseng/v0                                          -r $REPO --all --confirm
#conan upload libwebp/1.1.0@mercseng/v0                                          -r $REPO --all --confirm
#conan upload libxml2/2.9.9@mercseng/v0                                          -r $REPO --all --confirm
#conan upload llvm/3.5.1@mercseng/v1                                             -r $REPO --all --confirm
#conan upload llvm/13.0.1@mercseng/v0                                            -r $REPO --all --confirm
#conan upload lzma/5.2.4@mercseng/v1                                             -r $REPO --all --confirm
#conan upload m4/1.4.18@mercseng/v0                                              -r $REPO --all --confirm
#conan upload materialx/1.37.1@mercseng/v0                                       -r $REPO --all --confirm
#conan upload materialx/1.38.10@mercseng/v0                                       -r $REPO --all --confirm
#conan upload nasm/2.13.02@mercseng/v0                                           -r $REPO --all --confirm
#conan upload ncurses/6.2@mercseng/v0                                            -r $REPO --all --confirm
#conan upload ninja/1.10.0@mercseng/v0                                           -r $REPO --all --confirm
#conan upload OpenColorIO/1.1.1@mercseng/v0                                      -r $REPO --all --confirm
#conan upload OpenColorIO/2.0@mercseng/v2                                        -r $REPO --all --confirm
#conan upload OpenEXR/2.5.1@mercseng/v0                                          -r $REPO --all --confirm
#conan upload OpenExrId/1.0-beta.22@mercseng/v0                                  -r $REPO --all --confirm
#conan upload OpenImageDenoise/1.0.0@mercseng/v2                                 -r $REPO --all --confirm
#conan upload OpenImageDenoise/1.4.2@mercseng/v0                                 -r $REPO --all --confirm
#conan upload OpenImageIO/2.1.15.0@mercseng/v3                                   -r $REPO --all --confirm
#conan upload OpenSSL/1.1.1g@mercseng/v0                                         -r $REPO --all --confirm
#conan upload OpenSubdiv/3.4.3@mercseng/v1                                       -r $REPO --all --confirm
#conan upload OpenSubdiv/3.5.0@mercseng/v0                                       -r $REPO --all --confirm
#conan upload OpenVdb/4.0.2@mercseng/v2                                          -r $REPO --all --confirm
#conan upload OpenVdb/6.2.1@mercseng/v1                                          -r $REPO --all --confirm
#conan upload partio/1.7.4@mercseng/v0                                           -r $REPO --all --confirm
#conan upload pcre2/10.33@mercseng/v0                                            -r $REPO --all --confirm
#conan upload PortAudio/2018-12-24@mercseng/v0                                   -r $REPO --all --confirm
#conan upload ptex/2.3.2@mercseng/v0                                             -r $REPO --all --confirm
#conan upload pybind11/2.5.0@mercseng/v0                                         -r $REPO --all --confirm
#conan upload pystring/1.1.3@mercseng/v0                                         -r $REPO --all --confirm
#conan upload PySide2/5.12.6@mercseng/v7                                         -r $REPO --all --confirm
#conan upload python/2.6@mercseng/v1                                             -r $REPO --all --confirm
#conan upload python3/3.7@mercseng/v0                                            -r $REPO --all --confirm
#conan upload python3/3.10@mercseng/v0                                           -r $REPO --all --confirm
#conan upload python3.10_headers/3.10@mercseng/v0                                -r $REPO --all --confirm
#conan upload python-maquina/1.0.0@mercseng/v2                                   -r $REPO --all --confirm
#conan upload python-maquina-dev/1.0.0@mercseng/v2                               -r $REPO --all --confirm
#conan upload qt/5.12.6@mercseng/v6                                              -r $REPO --all --confirm
#conan upload rapidjson/1.1.0@mercseng/v0                                        -r $REPO --all --confirm
#conan upload re2/2019-06-01@mercseng/v1                                         -r $REPO --all --confirm
#conan upload readline/8.0@mercseng/v0                                           -r $REPO --all --confirm
#conan upload spdlog-rumba/1.5.0@mercseng/v0                                     -r $REPO --all --confirm
#conan upload sqlite3/3.32.3@mercseng/v0                                         -r $REPO --all --confirm
#conan upload tbb/2020.02@mercseng/v3                                            -r $REPO --all --confirm
#conan upload unistd/1.0@mercseng/v0                                             -r $REPO --all --confirm
#conan upload USD/20.05@mercseng/v4                                              -r $REPO --all --confirm
#conan upload USD/20.11@mercseng/v1                                              -r $REPO --all --confirm
#conan upload USD/20.11-rumba@mercseng/v6                                        -r $REPO --all --confirm
#conan upload USD/23.11-rumba@mercseng/v2                                        -r $REPO --all --confirm
#conan upload USD/24.11-rumba@mercseng/v1                                        -r $REPO --all --confirm
#conan upload winflexbison/2.5.22@mercseng/v0                                    -r $REPO --all --confirm
#conan upload wxwidgets/2.8.12@mercseng/v1                                       -r $REPO --all --confirm
#conan upload yaml-cpp/0.6.3@mercseng/v0                                         -r $REPO --all --confirm
#conan upload zlib/1.2.11@mercseng/v0                                            -r $REPO --all --confirm
#conan upload zstd/1.4.5@mercseng/v0                                             -r $REPO --all --confirm
