find_path(HARFBUZZ_INCLUDE_DIR NAMES harfbuzz/hb.h PATHS ${CONAN_INCLUDE_DIRS_HARFBUZZ} NO_CMAKE_FIND_ROOT_PATH)
find_library(HARFBUZZ_LIBRARY NAMES ${CONAN_LIBS_HARFBUZZ} PATHS ${CONAN_LIB_DIRS_HARFBUZZ} NO_CMAKE_FIND_ROOT_PATH)

MESSAGE("** HARFBUZZ ALREADY FOUND BY CONAN!")
SET(HARFBUZZ_FOUND TRUE)
MESSAGE("** FOUND HARFBUZZ:  ${HARFBUZZ_LIBRARY}")
MESSAGE("** FOUND HARFBUZZ INCLUDE:  ${HARFBUZZ_INCLUDE_DIR}")

set(HARFBUZZ_INCLUDE_DIRS ${HARFBUZZ_INCLUDE_DIR};${HARFBUZZ_INCLUDE_DIR}/harfbuzz)
set(HARFBUZZ_LIBRARIES ${HARFBUZZ_LIBRARY})

mark_as_advanced(HARFBUZZ_ROOT HARFBUZZ_LIBRARY HARFBUZZ_INCLUDE_DIR)

set(HARFBUZZ_MAJOR_VERSION "1")
set(HARFBUZZ_MINOR_VERSION "7")
set(HARFBUZZ_PATCH_VERSION "6")
